### ISSUE TITLE
ResourceManager test

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#1]
Write a proper test for the ResourceManager that tests the functionality of all its methods.

**Comment by svenstaro** [comment]
Progress?

**Comment by svenstaro** [comment]
Proooooogress?

**Comment by zetaron** [comment]
I'm on it but this week will not be realy productive becouse I'm at my mothers and am out of traffic.

**Comment by svenstaro** [comment]
Shouldn't that be all the more reason to be productive? No Reddit breaks for you!

**Comment by svenstaro** [comment]
This now depends on #22.

**Comment by svenstaro** [comment]
Reassigning to timesqueezer.

**Comment by opatut** [comment]
I shall do this for it has not been done within 2 months.
