### ISSUE TITLE
Implement disconnection and timeout behavior

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#10]

**Comment by opatut** [comment]
Nononono. You do not need to implement that in the chat sample, but in the engine itself (NetworkManager, GoodbyeEvent, etc.)

**Comment by svenstaro** [comment]
Updated to reflect actual goal more properly.

**Comment by svenstaro** [comment]
Progress?

**Comment by opatut** [comment]
Probably none. I take it.

**Comment by opatut** [comment]
Done. Also I had to implement Pings. Now we have them, too.
