### ISSUE TITLE
Implement scripting support

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#112]
This also requires evaluation of what we could even use. Chaiscript and Angelscript would be easy to integrate.

**Comment by opatut** [comment]
ChaiScript looks awesome! Angelscript seems a bit more complicated.

Each class would need a function to make it script-accessible (Interface!). Maybe we should abstract the scripting interface so we can support more than one language / scripting framework. All of this should be fairly easy :D

**Comment by opatut** [comment]
ChaiScript is header-only and compiles slow as hell :(

**Comment by svenstaro** [comment]
Depends on #114.
