### ISSUE TITLE
Get rid of OGRE glx icon warning

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#113]
The exception is apparently confusing quite a few people and we would like a neat icon in the window anyway.

**Comment by opatut** [comment]
Problem is - users will always need an icon file. This part is hard-coded in Ogre and cannot be turned off, AFAIK... We could try to provide an empty resource, though.

**Comment by opatut** [comment]
Depends on #125.

**Comment by shua** [comment]
Even if you provide a resource, the resource groups are added after that error comes up, so you still get the error. As far as I know there's no way to turn it off.

**Comment by shua** [comment]
aha, if you add the line 

```
Ogre::ResourceGroupManager::getSingletonPtr()->addResourceLocation("../data", "FileSystem", "General");
```

before mOgreRoot->createRenderWindow() is called at line 115 of DisplayManager.cpp, it will fix this. We should probably figure out a more generalized way to do this, in case the programmer wants to put his resources somewhere other than a data folder.

**Comment by svenstaro** [comment]
Yes, I figured that out as well but sadly due to our creation order this isn't trivial.

**Comment by shua** [comment]
maybe add a compile time definition like GLX_ICON or GLX_ICON_DIR?

**Comment by svenstaro** [comment]
Sounds hacky. :/

I got no better solution though.
