### ISSUE TITLE
Rename MessageEvent::GetMessageEvent() to GetMessageText

### ISSUE THREAD

**Issue by opatut** [ducttape/ducttape-engine#115]
... and fix all occurrences.

**Comment by clynamen** [comment]
Timer and ChatMessageEvent also have GetMessageEvent() method, should it be renamed, too?

**Comment by opatut** [comment]
Well, I noticed it does not inherit from ChatMessageEvent, even though it should... Could you do that as well? Make sure to call MessageEvent's constructor in the initializer list of ChatMessageEvent, then.

**Comment by clynamen** [comment]
I was adding to ChatMessageEvent the inheritance from MessageEvent, but it causes a diamond. Virtual inheritance seems to work fine, should I add it?

**Comment by opatut** [comment]
I see that diamond... If it works, it is fine! Go ahead.

**Comment by svenstaro** [comment]
Done.
