### ISSUE TITLE
Restructure GUI system

### ISSUE THREAD

**Issue by opatut** [ducttape/ducttape-engine#123]
Make the GUI independent from the component/node/scene system - so we can have GUI across scenes. Also, Nodes (3D) do not fit for Widgets(2D), and currently WidgetComponents cannot have children, because Components do not have children.

**Comment by shua** [comment]
Is anyone else having a problem compiling GuiTextBox.cpp? specifically the dynamic_cast's, I removed them and it makes it through, but then I get an error with MyGui::LogManager not having a function getInstance(), so I removed getInstance() (to see what would happen), and just left the STDOutputEnabled, which left other errors, I feel like I went the wrong way, but I don't know what the dynamic_cast's were doing.

**Comment by opatut** [comment]
Your MyGUI version is wrong. We changed to MyGUI 3.2. Depending on your OS you might need to compile it yourself from sources...

The dynamic casts were casting the Widget\* to EditBox\* so we could actually add event delegates. _EditBox_ is the new name of what was called _Edit_ in MyGUI 3.0, and they removed a few unnecessary typedefs. 3.2 will fix your problem, as it does for us :D

**Comment by shua** [comment]
Okay, thanks, seems like I'm up for a new kernel as well.
