### ISSUE TITLE
Make engine use signals/slots for most everything

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#128]
If the engine uses signals/slots for everything, we can have very interesting mid-tick interaction like controllers instantly updating physics, nodes, and so forth.

**Comment by opatut** [comment]
We could actually replace our event listeners. Can the qt signal/slot system be somehow manage priorities?

**Comment by svenstaro** [comment]
Yes, that is the plan. Qt supports this. Having basically 2 event loops when Qt does this better and quicker is pretty stupid.

**Comment by svenstaro** [comment]
Finally done.
