### ISSUE TITLE
Use Qt fast concatenation where possible

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#147]
Using the + operator for string concatenation should be replaced by % where possible. See here: http://doc.qt.nokia.com/latest/qstring.html#more-efficient-string-construction

I think using #define QT_USE_FAST_CONCATENATION in Config.hpp would be best for this.

**Comment by clynamen** [comment]
"QT_USE_FAST_CONCATENATION" will only work when it is defined before inclusion of QString.
QString is also included in test and samples, which doesn't include Config.hpp. So the compiling fails.
A possible solution is to include Config.hpp in every header that uses QString.

**Comment by svenstaro** [comment]
That seems reasonable. In fact, it probably is a good idea to include Config.hpp in every .hpp as we already include it in most .hpps anyway.

**Comment by svenstaro** [comment]
This is done, thanks clynamen.
