### ISSUE TITLE
MeshComponent/test_display broken

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#15]
This is a very strange bug. Somehow data in mSceneNode seems to get lost within the MeshComponent. Assigning a MeshComponent's mSceneNode manually in test_display and attaching its own mEntity to it makes it work. Does mSceneNode do some magic in Ogre and create something that we do not save in MeshComponent or is there something I am missing?

This needs investigation, it is a blocker.

**Comment by svenstaro** [comment]
This depends on #14.

**Comment by opatut** [comment]
Also this depends on #16.

**Comment by opatut** [comment]
It was as simple as the SceneNode not being attached to Ogre's Root scene node and also being rotated by Ogre::Quaternion::ZERO which is generally a bad idea. Better use Ogre::Quaternion::IDENTITY as default.
