### ISSUE TITLE
Component: FollowPath

### ISSUE THREAD

**Issue by opatut** [ducttape/ducttape-engine#17]
A path can be assigned to a node to follow.
### Required features / properties:
- Time for the path to complete _or_ speed [Done]
- Smooth interpolation [Done]
- Enable/disable "Follow rotation" [Done]
- Enable/disable smooth start/end (i.e. linear or smooth movement) [Done]
- Enable loop / forth-and-back [Done]

**Comment by opatut** [comment]
Started. Partially done. Still a bit buggy.

**Comment by svenstaro** [comment]
And please make a separate test_ for it. We will probably end up with many visual tests anyway.

**Comment by opatut** [comment]
> many visual tests

We should probably categorize them. And I'd still prefer a subfolder in bin/
