### ISSUE TITLE
Nodes never get initialized and inconsistent creation methods

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#175]
1. Nodes never get initialized. This can cause a lot of confusion.
2. We have Initialize/OnInitialize and Create/OnCreate which basically do the same. This is inconsistent. Prominently used in Node/Component.

**Comment by shua** [comment]
for 1 they get initialized on addChildNode. And I can fix 2 pretty easily. I'll switch them all to Create/OnCreate.

**Comment by svenstaro** [comment]
Status?

**Comment by shua** [comment]
Did it, but I think I deleted my repo before committing it's a 5-min fix though.
