### ISSUE TITLE
Consistently connect using QObject::connect or just connect or even CONNECT

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#177]
The current mix sucks. Make it consistent.

**Comment by shua** [comment]
pushed

**Comment by svenstaro** [comment]
After the last batch of commit we are inconsistent again. We should put this into the coding guidelines. After some deliberation, I think it would be best to use QObject::connect everywhere.

**Comment by shua** [comment]
Explicit? alright.
