### ISSUE TITLE
Register remaining core components

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#178]
Only TriggerComponent is currently being registered which obviously is not desirable as serialization will only work for this one. Register remaining components and perhaps expand the tests to match that. Writing this issue almost took longer than solving the problem will but this is a good junior dev task.

**Comment by svenstaro** [comment]
Thanks shua!

**Comment by shua** [comment]
Oh, I realize now that all the other components also have to be registered in Serializer::Initialize() in Serializer.cpp.

**Comment by svenstaro** [comment]
Go ahead :)
