### ISSUE TITLE
Change naming conventions

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#183]
With our ever stronger Qt usage and now [this](http://www.sfml-dev.org/forum/viewtopic.php?p=44120#44120) we should also adopt the general trend of C++ naming conventions.
- Make changes in code
- Make changes in coding standards doc
- Think about more changes:

lol() {
}

vs

lol()
{
}

etc.

**Comment by EternalWind** [comment]
Do you mean the same conventions as SFML 2.0 will use? camelCase for functions and public variables, getter without get/is prefix and m_prefix for class members?

**Comment by svenstaro** [comment]
Yes.

**Comment by svenstaro** [comment]
Whoops.

**Comment by svenstaro** [comment]
Sfml still hasn't received the new changes.

**Comment by svenstaro** [comment]
This is 50%.
