### ISSUE TITLE
Component: Sprite

### ISSUE THREAD

**Issue by opatut** [ducttape/ducttape-engine#21]
2D sprite. Basically a plane with a texture on it.

**Comment by opatut** [comment]
Would be cool to use SFML for this. I am on it!

**Comment by svenstaro** [comment]
We should use Ogre 2D sprites for this. If we need _real_ 2D, draw this offscreen to a texture using an orthogonal camera and render texture back to billboard.

**Comment by opatut** [comment]
We will have some problem, though, to render pixel-perfect, won't we?

**Comment by svenstaro** [comment]
Done.
