### ISSUE TITLE
Give ResourceManager smart way to find data dir

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#22]
Currently we only have simple relative paths. There should be a list iterating through:
- Current path, upwards (if we are in bin/, check ./data/, if not found, check ../data/, ../../data/ and so on
- System standard paths (/usr/share/$game_name/data)
- Compiled-in path (possibly DATA_PATH or similar during CMake)

**Comment by svenstaro** [comment]
The first bullet point of this is done. Others will have to follow in bigger samples. I'll let this issue open for now.

**Comment by svenstaro** [comment]
I want to close this. The 2 other bullet points should be implemented using data paths that are passed in from Game::Run(). They should be passed through as an optional `std::list<std::string>` right through Root::Initialize() and into the ResourceManager which should then fall back to those paths if the first strategy (finding the local data dir) fails.

There should also be a way to provide a different name for the currently hard-coded local data dir. Perhaps that `std::list<std::string>` should, if it is passed, just overwrite all hard-coded paths. This way, the ResourceManager can check whether the list contain's a relativ dir (without a beginning /) and prefer those first.

**Comment by svenstaro** [comment]
I'm assigning this to timesqueezer.

**Comment by opatut** [comment]
I shall do this one, too.
