### ISSUE TITLE
Use uint32_t internally to represent time instead of float

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#24]
Currently we convert the nice uint32_t we get from BeginFrameEvent::GetFrameTime() to float for the OnUpdate(float) methods. This way, the float will overflow within 2 1/2h. We should just use uint32_t for all time keeping.

**Comment by opatut** [comment]
You know we use Engines that are more precise... Maybe we sould have floats for time deltas and uint32_t for absolute times (i.e. lifetimes/time since Root::Initialize). We should not step a physics world with 300 FPS rounding to milliseconds. There will be up to 0.5 ms error per frame, which can lead to 0,15 s error per second on 300 FPS, or +- 15%. Not good for a physics simulation..

**Comment by svenstaro** [comment]
Good point. After all, float _is_ more accurate for fractions of a second than milliseconds are, however I would think that gettimeofday (which is what is used in unix-like systems) is no more accurate than 1ms at best. In fact, since most kernels tick at around 100 Hz by default, this resolution is only even achievable using dynamic ticks. I don't know whether most modern distributions default to dynamic ticks but they probably do. I don't know at all how accurate the Windows timer is.

Assuming we sometimes achieve < 1ms accuracy, how would we know? SFML fetches milliseconds only. Converting these milliseconds from uint32_t to float to do some calculation and hope it just got more accurate than doing straight integer arithmetic would seem hopeful at best if your source before conversion is uint32_t milliseconds. In fact, you would lose accuracy there unless you used multiplication/division.

Perhaps another consideration would be to make SFML query for nanoseconds (which gettimeofday allows) and make the time uint64_t? This would make the time fairly unreadable though. A Time class perhaps? We should discuss this further.

Besides, we clock the physics at a steady 60 FPS anyway.

**Comment by opatut** [comment]
At the moment, we usually tick at around 200 FPS (see [Game.cpp:39](https://github.com/svenstaro/ducttape-engine/blob/master/engine/src/game/Game.cpp#L39)). We get timediffs of 5-6 ms, which is ok, as we sleep 5 ms but also measure the time the frame takes to render etc. But in case we'd have > 1000 FPS for whatever we would only get 0ms timediffs, thus having no animation etc. at all. I don't know if SFML keeps the remaining nanoseconds in the sf::Clock on Reset(), if it is using `gettimeofday`, or doing something else. Maybe someone should check that.

I also dislike uint64_t for its ugliness. A Time class would be a solution, indeed.

As SFML now returns milliseconds and converting them to floats is pretty useless, we should consider using Ogre's Frame Events for time measurement. I believe they return floats anyway.

**Comment by svenstaro** [comment]
We decided to use double for all timing operations. This will give us an error of about 1ms per 100 days which is fair enough
