### ISSUE TITLE
Component::Deactivate is never actually called on destruction

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#25]
... which leads to race conditions with music destruction, for instance. This should really be called on Root shutdown.

**Comment by svenstaro** [comment]
Thinking about this further, we can currently not actually order the sequential destruction of components on Root::Deinitialize() because Root doesn't know them. This is actually a design problem since Root _does_ have a StateManager which is supposed to have States which are supposed to have Scenes which in turn have further Nodes which have Components.

Currently, we could only handle a destruction event but this would appear hacky given the other design considerations.

**Comment by opatut** [comment]
You are right. As the scenes are held by the states and are even optional, the states would have to manually deinitialize their scenes on destruct. The scenes could subscribe to a ScenesManager or something just for this issue. It would be conform to the other design decisions. 

We might also allow inheritance from Scenes. I like this idea, as it would work the same way as states and we would move Scene-Specific stuff away from the gamestate to the scene. In games with many different scenes this would clean up the code significantly.

**Comment by svenstaro** [comment]
Depends on #47.

**Comment by opatut** [comment]
Whoohaaa! I just closed 2 issues with 1 commit. How awesome!
