### ISSUE TITLE
Finalize automatic code packaging and test installation support

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#28]

**Comment by timesqueezer** [comment]
With CMake and svenstaro, this shouldn't be a big problem. ;)

**Comment by svenstaro** [comment]
I think I'm going to abandon CPack as it is too inflexible. A short shell script might be able to do its job much better.

**Comment by svenstaro** [comment]
I'm also considering using OpenBuildSystem to build the actual packages as this will ensure that the library is built against the proper versions of other system libraries for each distribution.

**Comment by svenstaro** [comment]
Done. This is now using a small custom script instead of CPack.
