### ISSUE TITLE
Finish implementation of GUI

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#51]
Evaluate GUI systems: We should either consider librocket or mygui for this.

**Comment by opatut** [comment]
I had a look at librocket, and the samples are kind of buggy for me. Also it segfaulted from time to time.

I have been using MyGUI for another project and I liked it quite much, it is basically made for Ogre and very flexible. Also its architecture integrates quite well in ours (we'd have a manager for the MyGUI::Gui instance and a Node for each widget). I guess I prefer MyGUI.

**Comment by opatut** [comment]
One more to evaluate: [Gorilla](http://www.ogre3d.org/forums/viewtopic.php?f=11&t=59984)

It is pretty cool, easy, fast, and allows the 2D stuff to be displayed in 3D space (see the example video). I think it is about... 20% cooler. It does not support ttf, though, which we might be able to fix by hand.

Sadly, it is not a real GUI but more a text/sprite rendering solution. We could combine it (for sprites) with MyGUI (for GUI).
