### ISSUE TITLE
Make a TextComponent and test_text

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#68]
Right now we have no way of displaying text on the screen. A component should be created to allow this. A test should be created to test these new facilities.

**Comment by svenstaro** [comment]
EternalWind will implement this.

**Comment by svenstaro** [comment]
Just to clarify, this should not replace or compete with a GUI! It's just 3D text that could be used for debugging information of nodes or such. Or perhaps even in simple games where adding a GUI would be too much.

**Comment by EternalWind** [comment]
I've studied the Ogre api but I havn't found any ways to implement a 3D text. It can only display 2D text like GUI using the Overlay which is always on top of the scene.

**Comment by svenstaro** [comment]
Ah, excuse me there, I think there was a miscommunication. I wanted you to implement 2D text on essentially a billboard or an overlay in 3D space.
See these links. The first link has an image of exactly what I wanted this to be:
http://www.ogre3d.org/tikiwiki/ObjectTextDisplay
http://www.ogre3d.org/tikiwiki/Simple+Text+Output&structure=Cookbook

**Comment by opatut** [comment]
I'm gonna do this now.
