### ISSUE TITLE
Use initializer lists instead of assignments

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#74]
Everybody's doing it and it saves creating a temporary. Also, it's the recommended way in C++. We should do it too.

**Comment by opatut** [comment]
I thought we agreed to only use them to call the Base class' constructor. So you think we should use them for all members?

**Comment by svenstaro** [comment]
Yes, it's likely the best solution after all. Especially with shared pointers that get passed around everywhere. It's also considered good practice. However, for now, use assignments. We'll change all of them in one big sweep.
