### ISSUE TITLE
Write test_shadow

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#84]
A simple test for showing different shadow techniques should be added. Possibly with moving nodes.

**Comment by svenstaro** [comment]
tomt610 will do this.

**Comment by svenstaro** [comment]
Please hurry with this, we want to get 0.1 out of the door reaaaally soon now.

**Comment by tomt610** [comment]
ok i will try, i got deadlines at work, projects got delayed there!

**Comment by opatut** [comment]
zetaron is nearly done with this.

**Comment by tomt610** [comment]
good i will notify you when i will get more time for task

**Comment by opatut** [comment]
Thank you, zetaron!
